---
# tasks file for show_changes
- name: Check for pending changes
  paloaltonetworks.panos.panos_op:
    provider: '{{ device }}'
       cmd: 'show config list changes'
      register: changes

- name: Display changes
  ansible.builtin.debug:
    msg: '{{ changes.stdout | from_json }}'

 - name: Commit changes if needed
   paloaltonetworks.panos.panos_commit:
      provider: '{{ device }}'
      when: >
        (changes.stdout | from_json).response.result.journal is defined and
        (changes.stdout | from_json).response.result.journal.entry | length > 0
